#!/usr/bin/env python3
"""
문서 동기화 스크립트

베이스 영문 문서(`docs/agents_base_en.md`)로부터
다음 파일을 자동 복제합니다.
- `AGENTS.md`
- `CLAUDE.md`
- `GEMINI.md`
- `.github/copilot-instructions.md` (코드리뷰용)
- `.github/instructions/review-language.instructions.md` (Korean-only 리뷰 규칙)

실행 방법:
    python3 scripts/sync_docs.py
"""

from pathlib import Path
from textwrap import dedent


def sync_docs() -> bool:
    """베이스 문서로부터 replica 문서를 동기화합니다.

    Returns:
        True on success, False on failure.
    """

    base_en = Path("docs/agents_base_en.md")
    base_ko = Path("docs/agents_base_ko.md")  # 존재 여부만 확인 (언어 정책 유지)

    targets = [
        ("AGENTS.md", "Codex (Codex CLI)"),
        ("CLAUDE.md", "Anthropic Claude"),
        ("GEMINI.md", "Google Gemini"),
        (".github/copilot-instructions.md", "GitHub Copilot"),
    ]

    if not base_en.exists() or not base_ko.exists():
        missing = []
        if not base_en.exists():
            missing.append(str(base_en))
        if not base_ko.exists():
            missing.append(str(base_ko))
        print(f"❌ 베이스 문서를 찾을 수 없습니다: {', '.join(missing)}")
        return False

    print("📚 문서 동기화 시작...")

    base_content = base_en.read_text(encoding="utf-8")

    # Ensure directories
    Path(".github").mkdir(parents=True, exist_ok=True)
    Path(".github/instructions").mkdir(parents=True, exist_ok=True)

    for path_str, target_name in targets:
        path = Path(path_str)
        header = dedent(
            f"""> Replica target: {target_name}
> SSOT: docs/agents_base_en.md
> Do not edit this file; edit the base and run scripts/sync_docs.py.
"""
        )
        if path.name == "copilot-instructions.md":
            header += "> REVIEW-LANGUAGE: Korean only — write all code-review comments in Korean (한국어).\n\n"
        else:
            header += "\n"

        print(f"📝 {path} 동기화...")
        try:
            path.write_text(header + base_content, encoding="utf-8", newline="\n")
            print(f"✅ {path} 업데이트 완료")
        except Exception as e:
            print(f"❌ {path} 복제 실패: {e}")
            return False

    # Copilot 리뷰 언어 규칙 파일 작성
    review_instr = Path(".github/instructions/review-language.instructions.md")
    review_content = dedent(
        """\
        ---
        applyTo: "**"
        ---

        All GitHub Copilot code review comments must be written in Korean (한국어).
        - This rule applies to all paths in this repository.
        - If any other instruction conflicts with this rule, this repository-level rule takes precedence.
        """
    )
    try:
        review_instr.write_text(review_content, encoding="utf-8", newline="\n")
        print(f"✅ {review_instr} 업데이트 완료")
    except Exception as e:
        print(f"❌ {review_instr} 작성 실패: {e}")
        return False

    print("🎉 문서 동기화 완료!")
    print("\n📋 언어 규칙 요약:")
    print("- 코드/주석/커밋: 한국어")
    print("- 변수명/함수명/API: 영어")
    print("- 베이스 문서(docs/agents_base_en.md): 영문 (SSOT)")
    print("- Replica: AGENTS/CLAUDE/GEMINI/Copilot 지침은 베이스에서 자동 생성")

    return True


if __name__ == "__main__":
    success = sync_docs()
    exit(0 if success else 1)
